const { contextBridge, ipcRenderer } = require("electron");

const forgeLinkShell = {
  notify: (title, body) => ipcRenderer.invoke("notify", { title, body }),
  notifyEvent: (event) => ipcRenderer.invoke("notify", event),
  attentionPolicy: () => ipcRenderer.invoke("attention-policy"),
  saveAttentionPolicy: (policy) => ipcRenderer.invoke("attention-policy-save", policy),
  openExternal: (url) => ipcRenderer.invoke("open-url", url),
  backendConnection: () => ipcRenderer.invoke("backend-connection"),
  getStatus: () => ipcRenderer.invoke("get-status"),
  validateSettings: (settings) => ipcRenderer.invoke("validate-settings", settings),
  startServer: (settings) => ipcRenderer.invoke("start-server", settings),
  startLocalOnly: (settings) => ipcRenderer.invoke("start-local-only", settings),
  startService: () => ipcRenderer.invoke("start-service"),
  importEnvironment: () => ipcRenderer.invoke("import-environment"),
  removeCredentials: () => ipcRenderer.invoke("remove-credentials"),
  smsProviderSettings: () => ipcRenderer.invoke("sms-provider-settings-get"),
  validateTelnyxSettings: (values) => ipcRenderer.invoke("telnyx-settings-validate", values),
  saveTelnyxSettings: (values) => ipcRenderer.invoke("telnyx-settings-save", values),
  selectSmsProvider: (provider) => ipcRenderer.invoke("sms-provider-select", provider),
  removeTelnyxSettings: () => ipcRenderer.invoke("telnyx-settings-remove"),
  stopServer: () => ipcRenderer.invoke("stop-server"),
  mcpStatus: () => ipcRenderer.invoke("mcp-status"),
  createMcpToken: () => ipcRenderer.invoke("mcp-create-token"),
  revokeMcpToken: () => ipcRenderer.invoke("mcp-revoke-token"),
  testMcpBridge: () => ipcRenderer.invoke("mcp-test-message"),
  agentChannels: () => ipcRenderer.invoke("agent-channels"),
  createAgentChannel: (payload) => ipcRenderer.invoke("agent-channel-create", payload),
  rotateAgentChannel: (channelId) => ipcRenderer.invoke("agent-channel-rotate", channelId),
  revokeAgentChannel: (channelId) => ipcRenderer.invoke("agent-channel-revoke", channelId),
  setAgentChannelEnabled: (channelId, enabled) => ipcRenderer.invoke("agent-channel-enabled", channelId, enabled),
  localIntegrations: () => ipcRenderer.invoke("local-integrations"),
  createLocalIntegration: (payload) => ipcRenderer.invoke("local-integration-create", payload),
  updateLocalIntegration: (integrationId, payload) => ipcRenderer.invoke("local-integration-update", integrationId, payload),
  rotateLocalIntegration: (integrationId) => ipcRenderer.invoke("local-integration-rotate", integrationId),
  revokeLocalIntegration: (integrationId) => ipcRenderer.invoke("local-integration-revoke", integrationId),
  setLocalIntegrationEnabled: (integrationId, enabled) => ipcRenderer.invoke("local-integration-enabled", integrationId, enabled),
  testLocalIntegration: (integrationId) => ipcRenderer.invoke("local-integration-test", integrationId),
  emailSettings: () => ipcRenderer.invoke("email-settings-get"),
  saveEmailSettings: (values) => ipcRenderer.invoke("email-settings-save", values),
  removeEmailSettings: () => ipcRenderer.invoke("email-settings-remove"),
  pushSettings: () => ipcRenderer.invoke("push-settings-get"),
  savePushSettings: (values) => ipcRenderer.invoke("push-settings-save", values),
  removePushSettings: () => ipcRenderer.invoke("push-settings-remove"),
  onServerStatus: (callback) => ipcRenderer.on("server-status", (_, status) => callback(status))
};

contextBridge.exposeInMainWorld("forgeLinkShell", forgeLinkShell);
contextBridge.exposeInMainWorld("desktop", forgeLinkShell);
